@extends('layouts.main')

@section('content')


<div class="campaign-terms-and-conditions-wrapper mt-5 mb-5 pb-5">
	<div class="container">
		<div class="row row-offcanvas row-offcanvas-right">
			<div class="col-12 col-md-9">
				<div class="jumbotron">
                                    <h1>Airport Assistance by MUrgency <br> Terms & Conditions </h1>

				</div>
				<div class="row">
					<div class="col-md-12 text-justify">
						<p><strong>TERMS OF AGREEMENT &amp; PRIVACY POLICY</strong></p>
						<p><strong>Updated as on 01 Feb, 2018</strong></p>
						<p>The following terms and conditions (the &ldquo;Terms of Use&rdquo;) are the Terms of Use for our app: &ldquo;Airport Assist by MUrgency&rdquo; (the &ldquo;App&rdquo;) and website: &ldquo;<a href="http://www.AirportAssistbyMUrgency.com">www.AirportAssistbyMUrgency.com</a>&rdquo; (the &ldquo;Site&rdquo;) made available by MUrgency Inc. (&ldquo;AirportAssist&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo;).</p>
						<p>The contents of the App and Site include, without limitation, all information, data, products, materials, services, software applications and tools, design elements, text, images, photographs, illustrations, audio and video contents, artwork, graphics contained therein or otherwise made available to you in connection therewith (collectively the &ldquo;Content&rdquo;) and, unless the context clearly requires otherwise, or we explicitly say so in writing, the term &ldquo;App&rdquo; and &ldquo;Site&rdquo; includes all of the Content.</p>
						<p>Accepting the Terms of Use and Additional Terms:</p>
						<p>The Terms of Use describe the terms and conditions applicable to your access and use of the App and Site. By browsing, accessing and/or using the App or Site or any Content in any manner, you acknowledge that you have read and accept and agree to be bound by these Terms of Use. Before continuing to use the App or Site, please read these Terms of Use and contact us if you have any questions. These Terms of Use constitute a legally binding agreement between you and MUrgency Inc. regarding your use of and access to the App and Site.</p>
						<p>MUrgency Inc. reserves the right to amend, modify and supplement these Terms of Use from time to time as it sees fit with additional terms and conditions that govern certain information, content, products and services made available to you via the App and Site (&ldquo;Additional Terms&rdquo;). By accessing and using the App and Site, you accept and agree to comply with and be bound by such Additional Terms. Please review these Terms of Use from time to time to ensure that you are aware of and understand any Additional Terms. Changes to this Agreement will not be applied retroactively.</p>
						<p>The Additional Terms, the Privacy Policy and the Copyright Notice (<a href="http://AirportAssistby">http://AirportAssistby</a> MUrgency.com/privacy.html) are hereby incorporated by reference into these Terms of Use and form part of the legally binding agreement between you and us. To the extent that there is a conflict between these Terms of Use and any Additional Terms, the Additional Terms shall govern. These Terms of Use will remain in full force and effect as long as you are a user of the App and / or the Site and, in the event of termination of any product, service or feature, you will still be bound by your obligations under these Terms of Use, the Privacy Statement, the Copyright Statement and any Additional Terms.</p>
						<p>Provision of the App and the Site by MUrgency Inc.</p>
						<p>You acknowledge and agree that the form and nature of the App and / or the Site may change from time to time without prior notice to you.</p>
						<p>You acknowledge and agree that MUrgency Inc. may stop (permanently or temporarily) providing the App and / or the Site (or any features within the App and / or the Site) to you or to users generally, at MUrgency&rsquo;s sole discretion, without prior notice to you. You may stop using the App and / or the Site at any time. You do not need to inform MUrgency Inc. when you stop using the App and / or the Site or any of its features.</p>
						<p>MUrgency Inc. makes no claims that the Content of the App and / or the Site may be downloaded outside of USA. If you access the App and / or the Site from outside of the United States of America, you do so at your own risk and are responsible for compliance with the laws of the country or other territory in which you are located.</p>
						<p>Use of the App and / or the Site by You</p>
						<p>You may use the App and / or the Site and the Contents therein solely for your non-commercial and limited personal use and for no other purposes. So long as you agree and comply with the Terms of Use, and unless this Agreement is otherwise terminated by MUrgency Inc., MUrgency Inc. invites you to view and / or print a single copy of the App and / or the Site and the Contents therein.</p>
						<p>You agree that you will not remove or modify any acknowledgements, credits or legal notices contained on the App and / or the Site or in the Contents therein. Special terms may apply to some services offered on the App and / or the Site and may be posted in connection with the applicable service, feature or activity. Any such terms are in addition to these Terms of Service and, in the event of a conflict, any such terms shall prevail.</p>
						<p>You agree not to access the App and / or the Site by any means other than through a standard web browser on a computer or mobile device. You further agree that you will not damage, disable, overburden, or impair the App and / or the Site or interfere with any other party's use and enjoyment of it.</p>
						<p>Your use of the App and / or the Site is subject to all applicable local, provincial, state and federal laws and regulations.</p>
						<p>You agree that you are solely responsible for (and that MUrgency Inc. has no responsibility to you or to any third party for) any breach of your obligations under these Terms of Use and for the consequences (including any loss or damage which MUrgency Inc. may suffer) of any such breach.</p>
						<p>Links to Third-Party Sites</p>
						<p>Use of certain links on the App and / or the Site will direct you away from the App and / or the Site to third party apps / websites. Such third party websites are not under the control of MUrgency Inc., and MUrgency Inc. is not responsible for the contents of any such app / website or any link contained in such app / website. The third party links included on the App / Site are provided for your convenience, and the inclusion of such links does not imply a recommendation or endorsement by MUrgency Inc. of any such app / website or the products or services offered therein. If you decide to access any of the third party apps / websites linked to the App and / or the Site, you do so entirely at your own risk. You acknowledge and agree that MUrgency Inc. shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by, or in connection with the use of or reliance on any such third party apps / websites.</p>
						<p>Privacy and Personal Information</p>
						<p>IP Address. MUrgency Inc. servers collect information specific to how you use the Internet. MUrgency Inc. servers note details such as the server you are logged onto and your IP address. We collect your IP (Internet Protocol) address to help diagnose problems with our server, and to administer our Site. An IP address is a number that is assigned to your computer when you use the Internet. This information does not contain any personally identifiable information about you. Your IP address is also used to help identify you during a particular session and to gather broad demographic data. This information is obtained solely for the purpose of maintaining the Site's integrity and improving our service.</p>
						<p>Cookies. &ldquo;Cookies&rdquo; are pieces of information that are placed on an individual's computer hard drive / mobile device to enable the individual to more easily communicate and interact with the Site. Currently we do not use cookies however MUrgency Inc. reserves the rights to introduce the usage of cookies to customize your experience on the App / Site. In the future, we may use cookies to record how many times a user has visited our App / Site and what pages the user has accessed. You may, however, disallow receiving cookies at any time through your web browser / mobile device. It is not our intention to use cookies to retrieve information that is unrelated to our App / Site or your interaction with our App / Site.</p>
						<p>App / Site Usage. MUrgency Inc. and its affiliates use information collected on and through the App / Site to comply with the purpose for which such information was collected and other purposes, as disclosed at the time such information is provided, or as described herein or in the Privacy Policy. For example, the information collected on and through the App / Site may be used to send you information about our and our affiliates' products and services and updates to our App / Site. In certain instances, you will have an opportunity to limit this use at time the information is collected. We may use the information we gather along with information obtained from other sources, including third parties.</p>
						<p>We may use the information collected on and through the App / Site to improve our App / Site and to send you information that may be of interest to you. We may share this information with others, such as advertisers interested in advertising on the App / Site. This information may also be used to evaluate what portions of the App / Site are more popular than others, determine where visitors came from, and where they go, and how long visitors stay on a particular page, or the App / Site in general.</p>
						<p>Surveys. MUrgency Inc. may ask you for more personal information from time to time in a survey format. This information is specifically used to ensure that the App / Site is up-to-date and relevant, and that the products and services provided to you in advertising format are relevant and of interest to you. Any information used as demographics will not reveal the source, and will be kept secure. This further information provided by you is on an optional basis.</p>
						<p>Privacy Policy. By agreeing to the Terms of Use, you acknowledge that MUrgency Inc. may collect, use and disclose your information as described in our Privacy Policy. This policy explains how MUrgency Inc. treats your personal information, and protects your privacy, when you use the App / Site.</p>
						<p>Ownership of Intellectual Property Rights</p>
						<p>The App / Site together with all trade-marks and other intellectual property displayed, distributed, or otherwise made available via the App / Site, is the exclusive property of MUrgency Inc., and its successors, assigns, licensors, and/or suppliers. Unless you have agreed otherwise in writing with MUrgency Inc., nothing in these Terms of Use gives you a right to use any of the Content, MUrgency Inc.&rsquo;s trade-marks or other intellectual property of MUrgency Inc.. You may not assign or transfer any of the Content and you may not grant a license to use or access the App / Site to any party.</p>
						<p>No information or statement contained in these Terms of Use or the App / Site shall be construed as conferring, directly or by implication, estoppel or otherwise, any license or right under any patent, copyright, trade-mark, or other intellectual property right of MUrgency Inc. or any third party. You must not alter, delete, or conceal any copyright or other notices contained on the App / Site, including notices on any of the Content that you are permitted to download, transmit, display, print, or reproduce from the App / Site.</p>
						<p>You may not allow any third party (whether or not for your benefit) to reproduce, modify, create derivative works from, display, perform, publish, distribute, disseminate, broadcast or circulate to any third party (including, without limitation, on or via a third party website), or otherwise use, any Content without the express prior written consent of MUrgency Inc. or its owner if MUrgency Inc. is not the owner.</p>
						<p>Any unauthorized or prohibited use of any Content may subject you to civil liability, criminal prosecution, or both, under applicable federal, provincial, state and local laws.</p>
						<p>You may not create a link to the App / Site without MUrgency Inc. prior permission. We may, however, if requested, grant a limited, nonexclusive right to create a link to the App / Site provided that such link is to the entry page of the App / Site and does not portray MUrgency Inc. or any of its activities or services in a false, misleading, derogatory, or otherwise negative manner.</p>
						<p>The limited rights granted to you under these Terms of Use may be revoked by MUrgency Inc. at any time for any reason whatsoever.</p>
						<p>Third-Party Information</p>
						<p>Any third-party content, data or publications made available through the App / Site are furnished by MUrgency Inc. on an as-is basis for your convenience and information. For example, we may include blogs within the App / Site on which the opinions of users or other persons may be expressed relating to travelling and the travel and leisure industry. Any opinions, advice, statements, services, offers, or other information made available by third parties, including program hosts, information providers, or any user of the Site, are those of the respective author(s) or publisher(s) and not of MUrgency Inc. MUrgency Inc. DISCLAIMS ANY WARRANTY OR REPRESENTATION, EITHER EXPRESS OR IMPLIED, THAT THE INFORMATION IN SUCH PUBLICATIONS IS ACCURATE OR COMPLETE AND YOU ACKNOWLEDGE AND AGREE THAT MUrgency Inc. IS NOT RESPONSIBLE FOR ANY LOSS OR DAMAGES THAT MAY BE CAUSED AS THE RESULT OF MATERIALS EXPRESSED IN SUCH PUBLICATIONS, INCLUDING ANY BLOGS.</p>
						<p>No Warranty</p>
						<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE APP / SITE IS AT YOUR SOLE RISK AND THAT THE APP / SITE AND THE CONTENT IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. MUrgency Inc. FURTHER EXPRESSLY DISCLAIMS ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
						<p>WE MAKE NO REPRESENTATIONS OR WARRANTIES THAT USE OF THE APP / SITE WILL BE UNINTERRUPTED OR ERROR-FREE. YOU ARE RESPONSIBLE FOR TAKING ALL NECESSARY PRECAUTIONS TO ENSURE THAT ANY CONTENT YOU MAY OBTAIN FROM THE APP / SITE IS FREE OF VIRUSES OR OTHER HARMFUL CODE.</p>
						<p>ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE APP / SITE IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</p>
						<p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM MUrgency Inc. OR THROUGH OR FROM THE APP / SITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THESE TERMS OF USE.</p>
						<p>Limitation of Liability</p>
						<p>SUBJECT TO SECTIONS ABOVE, YOU EXPRESSLY UNDERSTAND AND AGREE THAT MUrgency Inc., AND ITS LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL CONSEQUENTIAL OR EXEMPLARY DAMAGES WHICH MAY BE INCURRED BY YOU IN CONNECTION WITH YOUR USE OF THE APP / SITE, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY INCLUDING, BUT NOT LIMITED TO, ANY LOSS OF PROFIT, LOSS OF GOODWILL OR BUSINESS REPUTATION, LOSS OF DATA SUFFERED, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR OTHER INTANGIBLE LOSS.</p>
						<p>THE LIMITATIONS ON MUrgency Inc&rsquo;s LIABILITY TO YOU IN THIS SECTION SHALL APPLY WHETHER OR NOT MUrgency Inc. HAS BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING.</p>
						<p>Indemnification</p>
						<p>You agree to indemnify, defend, and hold harmless MUrgency Inc. and its successors and assigns, and any of their respective officers, directors, employees, members, agents, representatives, licensors, advertisers, and suppliers from any liability, loss, claim, and expense (including reasonable legal fees) related to (a) your violation of these Terms of Use, and (b) your use of the App / Site.</p>
						<p>We reserve the right to assume, at our sole expense, the exclusive defense and control of any such claim or action and all negotiations for settlement, or compromise, and you agree to fully cooperate with us in the defense of any such claim, action, settlement or compromise negotiations, as we may request.</p>
						<p>General</p>
						<p>These Terms of Use, together with any Additional Terms, the Privacy Policy and the Copyright Notice constitute the entire agreement between you and MUrgency Inc. relating to your use and our provision of the App / Site.</p>
						<p>You agree that MUrgency Inc. may provide you with notices, including those regarding changes to these Terms of Use, by email, regular mail, or postings on the App / Site.</p>
						<p>You agree that if MUrgency Inc. does not exercise or enforce any legal right or remedy which is contained in these Terms of Use (or which MUrgency Inc. has the benefit of under any applicable law), this will not be taken to be a formal waiver of MUrgency Inc.&rsquo;s rights and that those rights or remedies will still be available to MUrgency Inc..</p>
						<p>If any provision of these Terms of Use is held to be illegal, invalid or unenforceable, this will not affect any other provision of these Terms of Use and the agreement between you and us will be deemed amended to the extent necessary to make it legal, valid, and enforceable.</p>
						<p>The laws of the State of California and the federal laws applicable therein shall govern these Terms of Use in all respects, without giving effect to conflicts of laws principles. YOU AGREE THAT NO CLAIM ARISING OUT OF THIS AGREEMENT OR YOUR USE OF THE APP / SITE MAY BE BROUGHT AS A CLASS ACTION.</p>
						<p>Any cause of action or claim you may have with respect to the Terms of Use or the App / Site must be commenced within six (6) months after the claim or cause of action arises or such claim or cause of action shall be barred.</p>
						<p>No e-mail address found on the App / Site may be harvested or otherwise used for purposes of solicitation.</p>
						<p>Contacting MUrgency Inc.</p>
						<p>To contact, or to request the consent of, MUrgency Inc. for any of the actions for which such consent is required under these Terms of Use, please send an e-mail to legal@MUrgency.com. MUrgency Inc. reserves the right to refuse any such requests in its sole discretion.</p>
					</div>
				</div>
			</div>
		</div>
		<hr>
	</div>
</div>
@endsection
